# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBattlepokemon():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_battlepokemon(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1197, 1032)
    self.driver.find_element(By.LINK_TEXT, "Выбрать").click()
    self.driver.find_element(By.NAME, "userimput").send_keys("2")
    self.driver.find_element(By.NAME, "userimput").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(9) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(7) > span").click()
    self.driver.find_element(By.LINK_TEXT, "Начать новую битву").click()
    self.driver.find_element(By.NAME, "userimput").send_keys("2")
    self.driver.find_element(By.NAME, "userimput").click()
    self.driver.find_element(By.NAME, "userimput").send_keys("3")
    self.driver.find_element(By.NAME, "userimput").click()
    element = self.driver.find_element(By.NAME, "userimput")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(9) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(7) > span").click()
  
